# Your Solution

version: '3.8'

services:
  book_catalog:
    image: book_catalog:1
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://inventory_knse_user:W6PKDpgHHJ9VUzHmkMqJuUEnc0mkqfge@dpg-crmf2iq3esus73fs09r0-a.oregon-postgres.render.com/inventory_knse
    restart: "no"
    

  inventory_management:
    image: inventory_management:1
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    ports:
      - "8001:80" 
    environment:
      - DATABASE_URL=postgresql://inventory_knse_user:W6PKDpgHHJ9VUzHmkMqJuUEnc0mkqfge@dpg-crmf2iq3esus73fs09r0-a.oregon-postgres.render.com/inventory_knse
    restart: "no"