# Your Solution

version: '3.8'

services:
  book_catalog:
    image: book_catalog:1
    build: 
      context: ./book_catalog
      platforms:
      - "linux/amd64"
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://part03_user:qjwuMVamfmrDdtBe89v2RXpKSVtwn1aI@dpg-crqejpu8ii6s73ctectg-a.oregon-postgres.render.com/part03
    restart: "no"
    

  inventory_management:
    image: inventory_management:1
    build: 
      context: ./inventory_management
      platforms:
      - "linux/amd64"
      dockerfile: Dockerfile
    ports:
      - "4001:4001" 
    environment:
      - DATABASE_URL=postgresql://part03_user:qjwuMVamfmrDdtBe89v2RXpKSVtwn1aI@dpg-crqejpu8ii6s73ctectg-a.oregon-postgres.render.com/part03
    restart: "no"